# reference: https://docs.python.org/zh-cn/3/library/logging.config.html#dictionary-schema-details
version                  = 1
incremental              = false
disable_existing_loggers = false


[formatters.default]
class    = "logging.Formatter"
format   = "[{asctime}.{msecs:03.0f}] {levelname:<5} | {threadName} | {module}:{funcName}:{lineno} | {message}"
datefmt  = "%Y-%m-%d %H:%M:%S"
style    = "{"
validate = true
defaults = {}
maxsize  = 1024


[handlers.stdout]
class     = "logging.StreamHandler"
level     = "DEBUG"
formatter = "default"


[handlers.file]
class       = "logging.handlers.RotatingFileHandler"
level       = "DEBUG"
formatter   = "default"
filename    = "logs/app.log"
maxBytes    = 10_485_760 #10MB
backupCount = 5
encoding    = "utf8"


[loggers.default]
level    = "DEBUG"
handlers = ["stdout", "file"]